external/meta-mender-tegra: drop overrides for state scripts
that are now obsolete and have been removed upstream, and
update the commit-check script to use tegra-boot-tools.

Signed-off-by: Matt Madison <matt@madison.systems>

diff --git a/layers/meta-testdistro/external/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot b/layers/meta-testdistro/external/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot
--- a/layers/meta-testdistro/external/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot
+++ b/layers/meta-testdistro/external/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot
@@ -14,7 +14,8 @@ fi
 # If the rootfs partitions are eMMC/SDcard device names, verify that
 # the mender boot partition in U-Boot and the Tegra bootloader boot
 # slot match.  If not, the Tegra bootloader update failed, and we
-# need to have Mender roll us back.
+# need to reset the boot slot to get the Tegra bootloader and Mender
+# resynchronized.
 if [ "${devnam##/dev/mmcblk}" != "${devnam}" ]; then
     bootpart=`fw_printenv -n mender_boot_part`
     if [ -z "$bootpart" ]; then
@@ -27,7 +28,10 @@ if [ "${devnam##/dev/mmcblk}" != "${devnam}" ]; then
 	exit 1
     fi
     if [ $bootpart -ne $devnampart ]; then
-	echo "Detected Tegra bootloader upgrade failure" >&2
+	altslot=$(expr 1 - $curslot)
+	echo "Detected Tegra bootloader upgrade failure, resetting boot slot to $altslot" >&2
+	echo "*** Reboot required ***" >&2
+	tegra-boot-control --set-active $altslot
 	exit 1
     fi
 fi
